# Generated by Django 5.1.5 on 2025-01-29 02:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('registered_at', models.DateTimeField(default=datetime.datetime(2025, 1, 29, 2, 34, 29, 20233, tzinfo=datetime.timezone.utc))),
                ('github_url', models.URLField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
