# Generated by Django 5.1.5 on 2025-01-29 03:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registered_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 3, 18, 8, 945817, tzinfo=datetime.timezone.utc)),
        ),
    ]
