# Generated by Django 5.1.5 on 2025-01-29 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0002_alter_user_registered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registered_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 3, 47, 36, 746762, tzinfo=datetime.timezone.utc)),
        ),
    ]
